version: "3"
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=ww_user
      - MARIADB_DATABASE=workweather
  api:
    image: docker.io/bitnami/laravel:9
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=ww_user
      - DB_DATABASE=workweather
    volumes:
      - "./api:/app"
    depends_on:
      - mariadb
  web:
    build:
      context: ./docker/web
    volumes:
      - './web:/work-weather'
      - '/app/node_modules'
    ports:
      - 3000:3000
    depends_on:
      - api